### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by kavanase** [SMTG-UCL/defect-finder#6]
It's been suggested `defect-finder` sounds too similar to interstitial position locators, so something more focused on the symmetry-breaking / distortion behaviour might be better.

What about `ShakeNBreak`? As we're `shak`ing the atoms and `break`ing the symmetry? If you're happy with this @ireaml, then I can rename to this.

**Comment by kavanase** [comment]
I checked and this name is free on `PyPi`, and there doesn't seem to be any other packages / codes that we'd be competing against with this name

**Comment by ireaml** [comment]
ShakeNBreak sounds great!!

**Comment by kavanase** [comment]
Cool, will rename to this so! 😃 
And claim the name on `PyPi`
